#pragma once

// Unicode Configuration
#define UNICODE_KEY_MAC KC_LEFT_ALT
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_KEY_WINC KC_RIGHT_ALT
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_LINUX
#define UNICODE_CYCLE_PERSIST true
#define UNICODE_TYPE_DELAY 10

#define UNICODE_SONG_WINC SONG(ALL_START_SHORT)
#define UNICODE_SONG_LNX SONG(RENAI_CIRCULATION_INTRO)